[package]
name = "bevy-glxf-loader"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.17.2"
serde_json = "1"
thiserror = "2"

[dependencies.serde]
version = "1"
features = ["derive"]

[dev-dependencies]
bevy-inspector-egui = "0.34"
bevy_egui = "0.37"
