[package]
name = "bevy-glxf-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
serde_json = "1"
thiserror = "2"

[dependencies.serde]
version = "1"
features = ["derive"]

[dev-dependencies]
bevy-inspector-egui = "0.25"
bevy_egui = "0.28"
